name: CPP project with Catch2 CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run clang format
        run: "find . -iname *.h -o -iname *.hpp -o -iname *.cpp -exec clang-format --dry-run --Werror -style=file {} +"

      - name: Build default
        run: mkdir build && cmake -S. -Bbuild -DUSE_CLANG_TIDY=TRUE -DTESTS_BUILD_TYPE=NONE -DCMAKE_BUILD_TYPE=Release && cmake --build build
      - name: Run default tests
        timeout-minutes: 5
        working-directory: ./build/lib/fractional
        run: ./tests

      - name: Build ASAN
        run: mkdir build_ASAN && cmake -S. -Bbuild_ASAN -DTESTS_BUILD_TYPE=ASAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_ASAN
      - name: Run ASAN tests
        timeout-minutes: 10
        working-directory: ./build_ASAN/lib/fractional
        run: ./tests

      - name: Build USAN
        run: mkdir build_USAN && cmake -S. -Bbuild_USAN -DTESTS_BUILD_TYPE=USAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_USAN
      - name: Run USAN tests
        timeout-minutes: 5
        working-directory: ./build_USAN/lib/fractional
        run: ./tests

      - name: Build MSAN
        run: mkdir build_MSAN && cmake -S. -Bbuild_MSAN -DTESTS_BUILD_TYPE=MSAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_MSAN
      - name: Run MSAN tests
        timeout-minutes: 5
        working-directory: ./build_MSAN/lib/fractional
        run: ./tests